# Message Queue

CC := gcc

all:
	$(CC) -o producer producer.c
	$(CC) -o consumerA consumerA.c
	$(CC) -o consumerB consumerB.c
	$(CC) -o client client.c 
	$(CC) -o server server.c 
clean:
	rm -rf  producer consumerA consumerB keyfile
